### ISSUE TITLE
subscribeLite leakage on iron:router route changes

### ISSUE THREAD

**Issue by andrewforage** [adtribute/pub-sub-lite#2] opened 2020-06-26 06:13 UTC
**Description**
`subscribeLite()` does not reset the minimongo collection on iron:router route change.

**Steps to reproduce**
1. Use `Meteor.subscribeLite('litePublication')` in an iron:router `waitOn()` or `subscriptions()`, e.g. /dashboard for my screenshot below
2. Assert the `subscibeLite` successfully loads the document into minimongo, e.g. `PublicProfiles.findOne()`
3. Perform an iron:router route change to a route **without a subscribeLite**, e.g. `Router.go('template')`
4. Assert that on this new route that the minimongo has not reset on a page without the `subscribeLite`

![image](https://user-images.githubusercontent.com/56419287/85826270-9b4b4e00-b7c7-11ea-9f44-e593ce8a599d.png)

**Comment by npvn** [comment] 2020-07-10 17:03
What you've described is indeed the expected behaviour of traditional Meteor pub/sub on route change. However, I think it is not a good pattern, because it can easily lead to unnecessarily repeated data transferring (e.g. user visits route A, then switches to route B, and then immediately switches back to route A and has to re-load all route A data again).

As the goal of pub-sub-lite is to minimize performance overhead, I decided not to automatically reset data. I will think more about whether we should provide a way to manually reset data later (see [this](https://github.com/adtribute/pub-sub-lite/issues/3) issue).

For now, I believe it should be enough to keep your data always up-to-date by:
- Avoiding generic queries (e.g. `collection.find({})`) on the client-side. Even when `collection` is expected to carry data specific to a particular route, we should always include query criteria because Minimongo by nature can contain data retrieved by other subscriptions/Methods intended for other routes.
- For pub-sub-lite, you probably shouldn't have to reset data on route change. To keep data up-to-date you only need to call a data fetching Method on route load and set an appropriate cache duration for it.

I will close the issue now. Please feel free to reopen and let me know if your use case requires further flexibility.

**Closed as completed by npvn** 2020-07-10 17:03 UTC
